### ISSUE TITLE
LivePoll Instructions and JS File differ regarding name of directory containing certificate files

### ISSUE THREAD

**Issue by xyztextbooks** [drlippman/IMathAS-Extras#3]
index.js is looking for a dir named "ssl"
`
var options = {
  key: fs.readFileSync(__dirname + '/ssl/privkey.pem'),
  cert: fs.readFileSync(__dirname + '/ssl/fullchain.pem'),
  ca: fs.readFileSync(__dirname + '/ssl/chain.pem')
};
`

Bt the instructions (and default path in  livepoll.sh file) refer to "certs"
`   livepoll_cert_root=/home/ubuntu/livepoll/certs`

**Comment by enoxos** [comment]
Has this question been answered? I am at the same point right now and not sure where to place the certificates.
Thanks

**Comment by drlippman** [comment]
Put the certificates wherever is convenient.  Just make sure the index.js file points to the files.  The files posted work for my server setup, but you'll need to modify them based on where you decide to put the files.

**Comment by enoxos** [comment]
Oh okay, will do that and report back soon.

**Comment by enoxos** [comment]
That worked, livepoll is up and running. I do have a small question however about the timer, should it also appear on the student view? I only see it on the instructor view. Not sure if this by design.
Thank you.

**Comment by drlippman** [comment]
Yes, the timer intentionally only shows for teachers right now.

**Comment by enoxos** [comment]
Ah okay, thanks for letting me know. Hopefully it will come back one day, it is a nice feature for the students to have.
