### ISSUE TITLE
LivePoll Answers table not updated properly with adjacent questions of type "choices"

### ISSUE THREAD

**Issue by xyztextbooks** [drlippman/IMathAS-Extras#4]
To reproduce:
- Create a LivePoll assessment
- add to the assessment several questions of type "choice" (in our tests the number of choices in each questions was 4)
- administer the test to students (with the option to "Show Answers" turned on

After the answers for the first questions are displayed, moving to the next question and opening it to students does not update the left column of the answers table (see attached screenshot).

![screenshots](https://user-images.githubusercontent.com/107379/90182742-4a87b880-dd67-11ea-8e71-e942b1deb03d.png)

**Comment by drlippman** [comment]
This has been fixed in the main IMathAS repo.
