### ISSUE TITLE
Pandoc datatmp directory

### ISSUE THREAD

**Issue by enoxos** [drlippman/IMathAS-Extras#6]
Hello,
I am a bit stuck in implementing Pandoc.  I copied the whole pandoc folder from the IMathAS-Extras as a new folder in the imathas root, namely `imathas/pandoc`. I also opened a /datatmp/ folder inside `/imathas/pandoc`.
After appropriate permissions, I changed the links in the `html2dcox.php` file to point in the /datatmp/ inside the pandoc folder. 
However the word file produced does not open in Microsoft word. When I open it with notepad, I get some warnings as follows:

`<b>Warning</b>:  filesize(): stat failed for ./datatmp/606fea8991aa7.docx in <b>/imathas/pandoc/html2docx.php</b> on line <b>118</b><br />`
<br />
`<b>Warning</b>:  readfile(./datatmp/606fea8991aa7.docx): failed to open stream: No such file or directory in <b>/imathas/pandoc/html2docx.php</b> on line <b>119</b><br />`

Any hints would be greatly appreciated. 

PS: I have installed Pandoc 2.5.

**Comment by drlippman** [comment]
My first guess is that the datatmp directory doesn't have write permission, so the script wasn't able to write the .html file in the first place.

**Comment by enoxos** [comment]
Thanks for the reply, but I do not think that is the issue. I checked the permissions and I even gave all permissions (777)  to the `/datatmp` folder, but still no luck.
I even installed pandoc 2.9 version, but still no luck.
What is the highest version pandoc has been tested with imathas? Perhaps I can try another version.
Thank you

**Comment by drlippman** [comment]
I can't remember exactly what version I'm using right now; I've used several over the years.  But it's highly unlikely it's the pandoc version causing the error.  

I'd suggest trying to run the command from line 111 manually on the command prompt to see what happens.  Perhaps you'll see an error that way that isn't revealed when the script is run online which will let you track down the source of the problem.

**Comment by zjevik** [comment]
Maybe this will help, maybe not. We had a similar problem because we run out instance on CentOS with SELinux enabled. Pandoc (through Apache user) is trying to access tmp folder and it couldn't access it even with 777 permissions because of the aforementioned SELinux policy.
Are you running Debian? I used to launch the command for Pandoc manually from Postman as @drlippman suggests and highly recommend testing it separately from imathas.

**Comment by enoxos** [comment]
Thank you both for your hints.
Here is what I did:
1) Run the command (modified 111 line form the html2docx.php file)
`/usr/bin/pandoc ../datatmp/6074dda1d2454.html -f html+tex_math_double_backslash --filter=pagebreak.php -o ../datatmp/word.docx` from the `imathas/pandoc/` directory. The `datatmp` is at the root of the imathas directory and it has 777 permissions. The `imathas/pandoc` directory is where the imathas pandoc files are stored, all with 777 permissions.
When I run the command, I get the following error:
PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in `/imathas/pandoc/pandocfilters.php:90`
Stack trace:
#0 `/imathas/pandoc/pagebreak.php(11): Pandoc_Filter::toJSONFilter()`
#1 {main}
thrown in /imathas/pandoc/pandocfilters.php on line 90
Error running filter pagebreak.php:
Filter returned error status 255

2) I run the installed Pandoc 2.9.2.1 version on its own again from `imathas/datatmp/` directory to test pandoc and file permissions:
`pandoc 6074dda1d2454.html -o word.docx`

and I get the proper docx output file. The 6074dda1d2454.html file was auto-generated from within the imathas site when I tried to print to docx. 

3)  I run Pandoc on its own again from `imathas/pandoc/` directory to test pandoc and file permissions:
`pandoc ../datatmp/6074dda1d2454.html -o word.docx`

and I get the proper output doxc file, again. 

So the installed Pandoc is working as I also testing couple other formats like md to html and txt to tex.

I am not sure what is going on right now, so I may have screwed up the whole Pandoc installation setting. Please bear with me, I am new to Ubuntu Linux servers (about a month of experience), so I may be doing something totally wrong.
Thank you!

**Comment by drlippman** [comment]
That sounds like there's some issue with the pagebreak filter, or the pandocfilters script.  Not sure why I haven't run into the same issue.   Actually, it looks like I may have modified the pandocfilters file and and forgot to update the repo.  I'll try to do that.

**Comment by drlippman** [comment]
If the fix I pushed up doesn't fix it, just remove the `--filter=pagebreak.php` from the exec command.  It's not really necessary.

**Comment by enoxos** [comment]
Sorry for the delayed reply, but some other things came up.
So after inserting the new code to the `html2docx.php` I got it to semi-work. 
One test printout with some of the stock examples gives a docx output so I know the setup is correct.
Another test printout with some other questions again from the stock examples, gives a new error:

` count(): Parameter must be an array or an object that implements Countable in <b>/imathas/pandoc/asciisvgimg.php</b> on line <b>511</b><br />`

So, there may be some more issues with the pandoc extra. I do not mind keep troubleshooting this so we can troubleshoot it.
Thank you

**Comment by drlippman** [comment]
Replace the `asciisvgimg.php` script with the one from the main imathas repo, in the `/filter/graph/` directory.  I don't always keep this "extras" repo up to date.

Edit: Scratch that, they have different requires at the top, and some other differences.  I'll try to correct the bug.

**Comment by enoxos** [comment]
That was fast, thank you for your efforts.
Will try the new code when it is uploaded and report back.

**Comment by enoxos** [comment]
Update: looks like the updated `asciisvgimg.php` fixed the `count(): Parameter must be an array or an object that implements Countable in <b>/imathas/pandoc/asciisvgimg.php</b> on line <b>511</b><br />` issue. 

I printed three new assignments with the stock example problems and all printed on docx.

Thank you so much.
